version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: payflow-db
    environment:
      POSTGRES_DB: payflow
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - payflow-network

  api:
    build: .
    container_name: payflow-api
    depends_on:
      - postgres
    environment:
      DATABASE_URL: jdbc:postgresql://postgres:5432/payflow
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
      SPRING_PROFILES_ACTIVE: docker
    ports:
      - "8080:8080"
    networks:
      - payflow-network

volumes:
  postgres_data:

networks:
  payflow-network:
    driver: bridge